package com.baidu.rigel.ring.bo;

import java.io.Serializable;
import java.util.Date;

public class Moved implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moved.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moved.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moved.moved_time
     *
     * @mbggenerated
     */
    private Date movedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moved.moved_place_x
     *
     * @mbggenerated
     */
    private Float movedPlaceX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moved.moved_place_y
     *
     * @mbggenerated
     */
    private Float movedPlaceY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_moved.heart_rate
     *
     * @mbggenerated
     */
    private Float heartRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_moved
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moved.id
     *
     * @return the value of tb_moved.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moved.id
     *
     * @param id the value for tb_moved.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moved.user_id
     *
     * @return the value of tb_moved.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moved.user_id
     *
     * @param userId the value for tb_moved.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moved.moved_time
     *
     * @return the value of tb_moved.moved_time
     *
     * @mbggenerated
     */
    public Date getMovedTime() {
        return movedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moved.moved_time
     *
     * @param movedTime the value for tb_moved.moved_time
     *
     * @mbggenerated
     */
    public void setMovedTime(Date movedTime) {
        this.movedTime = movedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moved.moved_place_x
     *
     * @return the value of tb_moved.moved_place_x
     *
     * @mbggenerated
     */
    public Float getMovedPlaceX() {
        return movedPlaceX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moved.moved_place_x
     *
     * @param movedPlaceX the value for tb_moved.moved_place_x
     *
     * @mbggenerated
     */
    public void setMovedPlaceX(Float movedPlaceX) {
        this.movedPlaceX = movedPlaceX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moved.moved_place_y
     *
     * @return the value of tb_moved.moved_place_y
     *
     * @mbggenerated
     */
    public Float getMovedPlaceY() {
        return movedPlaceY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moved.moved_place_y
     *
     * @param movedPlaceY the value for tb_moved.moved_place_y
     *
     * @mbggenerated
     */
    public void setMovedPlaceY(Float movedPlaceY) {
        this.movedPlaceY = movedPlaceY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_moved.heart_rate
     *
     * @return the value of tb_moved.heart_rate
     *
     * @mbggenerated
     */
    public Float getHeartRate() {
        return heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_moved.heart_rate
     *
     * @param heartRate the value for tb_moved.heart_rate
     *
     * @mbggenerated
     */
    public void setHeartRate(Float heartRate) {
        this.heartRate = heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moved
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Moved other = (Moved) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getMovedTime() == null ? other.getMovedTime() == null : this.getMovedTime().equals(other.getMovedTime()))
            && (this.getMovedPlaceX() == null ? other.getMovedPlaceX() == null : this.getMovedPlaceX().equals(other.getMovedPlaceX()))
            && (this.getMovedPlaceY() == null ? other.getMovedPlaceY() == null : this.getMovedPlaceY().equals(other.getMovedPlaceY()))
            && (this.getHeartRate() == null ? other.getHeartRate() == null : this.getHeartRate().equals(other.getHeartRate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_moved
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getMovedTime() == null) ? 0 : getMovedTime().hashCode());
        result = prime * result + ((getMovedPlaceX() == null) ? 0 : getMovedPlaceX().hashCode());
        result = prime * result + ((getMovedPlaceY() == null) ? 0 : getMovedPlaceY().hashCode());
        result = prime * result + ((getHeartRate() == null) ? 0 : getHeartRate().hashCode());
        return result;
    }
}